on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ assigned, opened, synchronize, reopened, labeled ]

name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)
  packages: write # to publish packages (npm publish)

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-bun
      - uses: ./.github/actions/build
      - run: bun test
      - run: bun run lint

  canary-release:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-bun
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"
      - uses: ./.github/actions/cache
        with:
          scope: build
      - run: npm version prerelease --preid=canary.$(git rev-parse --short HEAD) --no-git-tag-version
      - run: npm publish --tag canary
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
